// // prisma/seed.ts - Hospital Pharmacy V3.0 Complete System Seed
// // Generated by scripts/merge-seeds-updated.js
// // Do not edit manually - modify individual seed files instead

// import { PrismaClient } from "@prisma/client";
// import { hashPassword } from "../lib/auth";

// import { seedUsers } from "./seeds/users.seed";
// import { seedUnifiedCSV } from "./seeds/unified-csv.seed";

// const prisma = new PrismaClient();

// async function main() {
//   console.log("🌱 Starting Hospital Pharmacy V3.0 Seed...");
  
//   try {
//     // USER MANAGEMENT
//     console.log("👥 Creating users...");
    
    
//     const userResult = await seedUsers(prisma);
//     console.log(`✅ Users: ${userResult.totalUsers}`);
    

//     // DATA IMPORT
//     console.log("📁 Importing data...");
    
    
//     const csvResult = await seedUnifiedCSV(prisma);
//     console.log(`✅ Drugs: ${csvResult.drugs}, Stocks: ${csvResult.stocks}`);
    

//     // TRANSFER SYSTEM
//     console.log("🔄 Creating transfers...");
    
    
//     console.log("✅ Transfer system ready");
    

//     // VERIFICATION
//     console.log("🔍 Verifying system...");
//     const verification = await verifySystem(prisma);
    
//     console.log("="+"=".repeat(40));
//     console.log("🎉 Hospital Pharmacy V3.0 Ready!");
//     console.log(`📊 Users: ${verification.users}, Drugs: ${verification.drugs}`);
//     console.log(`📦 Stocks: ${verification.stocks}, Transfers: ${verification.transfers}`);
//     console.log("🚀 Next: npm run dev");

//   } catch (error) {
//     console.error("💥 Seed error:", error.message);
//     throw error;
//   } finally {
//     await prisma.$disconnect();
//   }
// }

// async function verifySystem(prisma: PrismaClient) {
//   try {
//     const [users, drugs, stocks, transfers] = await Promise.all([
//       prisma.user.count(),
//       prisma.drug.count(),
//       prisma.stock.count(),
//       prisma.transfer.count().catch(() => 0),
//     ]);

//     return { users, drugs, stocks, transfers };
//   } catch (error) {
//     console.error("❌ Verification failed:", error.message);
//     return { users: 0, drugs: 0, stocks: 0, transfers: 0 };
//   }
// }

// main()
//   .catch((e) => {
//     console.error("💥 FATAL ERROR:");
//     console.error(e.message);
//     process.exit(1);
//   })
//   .finally(async () => {
//     await prisma.$disconnect();
//   });

// export { prisma };